# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
       name: selfwindowsagent
       demands:
        - agent.name -equals SREE-PC
    steps:
    - task: Docker@2
      displayName: docker login
      inputs:
        containerRegistry: 'dockerhubconnection'
        command: 'login'
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          # Write your PowerShell commands here.
          
          Write-Host "Hello World"
